// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qdrtojbzrnqcnrhikcnq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFkcnRvamJ6cm5xY25yaGlrY25xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0OTAyODcsImV4cCI6MjA3MTA2NjI4N30.AylGjlPACmbB5iImta4-y9Uwsrq5EiFQXLTEFzzVlrM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});