name: Publish React Build to Main Repo Root

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout React Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Build React App
        run: npm run build

      - name: Clone Main Repo
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN || secrets.GITHUB_TOKEN }}
        run: |
          git clone https://github.com/sefgh-ai/hostSefgh.git ../main-repo
          cd ../main-repo
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Copy build output to main repo root and rename index.html
        run: |
          # Remove old build artifacts from main repo root (but keep .git/, .github/, and workflow files)
          cd ../main-repo
          find . -maxdepth 1 ! -name '.git' ! -name '.github' ! -name '.' ! -name '..' -type f -exec rm -f {} +
          find . -maxdepth 1 ! -name '.git' ! -name '.github' ! -name '.' ! -name '..' -type d -exec rm -rf {} +

          # Copy all files from the built dist folder into main repo root
          cp -r ../hostSefgh-react/dist/* .

          # Rename index.html to searchpage.html if exists
          if [ -f ./index.html ]; then
            mv ./index.html ./searchpage.html
          fi

      - name: Commit and Push to Main Repo
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN || secrets.GITHUB_TOKEN }}
        run: |
          cd ../main-repo
          git add .
          git commit -m "Publish React build to root (auto, ${{ github.sha }})" || echo "No changes to commit"
          git push https://x-access-token:${GH_TOKEN}@github.com/sefgh-ai/hostSefgh.git main
