name: Publish React Build to Main Repo Root

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout React Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Find package.json directory
        id: pkgdir
        run: |
          PKG_DIR=$(find . -type f -name package.json -not -path "*/node_modules/*" | head -n 1 | xargs dirname)
          echo "Found package.json in: $PKG_DIR"
          echo "pkgdir=$PKG_DIR" >> $GITHUB_OUTPUT

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd "${{ steps.pkgdir.outputs.pkgdir }}"
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Build React App
        run: |
          cd "${{ steps.pkgdir.outputs.pkgdir }}"
          npm run build

      - name: Find build output directory
        id: builddir
        run: |
          cd "${{ steps.pkgdir.outputs.pkgdir }}"
          # Prefer dist, fallback to build
          if [ -d dist ]; then
            echo "builddir=${{ steps.pkgdir.outputs.pkgdir }}/dist" >> $GITHUB_OUTPUT
          elif [ -d build ]; then
            echo "builddir=${{ steps.pkgdir.outputs.pkgdir }}/build" >> $GITHUB_OUTPUT
          else
            echo "No build output directory found!"
            exit 1
          fi

      - name: Clone Main Repo
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git clone https://github.com/sefgh-ai/hostSefgh.git ../main-repo
          cd ../main-repo
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Copy build output to main repo root and rename index.html
        run: |
          cd ../main-repo
          # Copy only the contents of the build output into the root
          cp -rf "${{ steps.builddir.outputs.builddir }}"/* .

          # Rename index.html to searchpage.html
          if [ -f ./index.html ]; then
            mv ./index.html ./searchpage.html
          fi

      - name: Commit and Push to Main Repo
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          cd ../main-repo
          git add .
          git commit -m "Publish React build to root (auto, ${{ github.sha }})" || echo "No changes to commit"
          git push https://x-access-token:${GH_TOKEN}@github.com/sefgh-ai/hostSefgh.git main
